spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webclasstemp
    username: root
    password: gyj990927
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
baiduai:
  appId: 25869006
  apiKey: HoMCcNGZsEbYXXuwvBPbqSyk
  secretKey: DYQQe6hhNsqBmx58UqrZxmf2ZKjZUjOw
bosai:
  ACCESS_KEY_ID: b192b1a6bb8d4bd4b8f8a3575b8ccec0
  SECRET_ACCESS_KEY: 5dfb7e1f5b0b4cc2a78318acdf5d35e5
  ENDPOINT: 2633564497.su.bcebos.com
